### ISSUE TITLE
Login is unsuccessful for accounts that use Two Step Verification

### ISSUE THREAD

**Issue by knightcube** [NITDgpOS/Medium_Grabber#23]
When I tried with an account that has Two Step Verification in their account settings, it did not login. As soon as the Two Step Verification was turned off, the program runs well and good. I have given the logs below. Can any functionality be added to bypass this problem?

```
Choose the browser you want to use:(Enter the appropriate number)

                1---> firefox

                2---> chrome

                0--->exit
2
1208/203550.580:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:51752/devtools/browser/b13cb79c-627f-4ddf-86d2-927692096027
[1208/203600.810:INFO:CONSOLE(0)] "Refused to connect to 'https://srv-2018-12-08-15.pixel.parsely.com/event/?rand=1544281560799&plid=80778101&idsite=medium.com&url=https%3A%2F%2Fmedium.com%2F&urlref=&screen=800x600%7C800x600%7C24&data=%7B%7D&sid=1&surl=https%3A%2F%2Fmedium.com%2F&sref=&sts=1544281556599&slts=0&date=Sat+Dec+08+2018+20%3A36%3A00+GMT%2B0530+(India+Standard+Time)&action=heartbeat&inc=4&tt=4101&u=pid%3Dd1df50a78549de27c3bb7da80df99acf' because it violates the following Content Security Policy directive: "connect-src https://localhost https://*.instapaper.com https://*.stripe.com https://glyph.medium.com https://*.paypal.com https://getpocket.com https://medium.com:443 https://*.medium.com:443 https://*.medium.com https://medium.com https://*.medium.com https://*.algolia.net https://cdn-static-1.medium.com https://dnqgz544uhbo8.cloudfront.net https://cdn-videos-1.medium.com https://cdn-audio-1.medium.com https://*.lightstep.com https://*.branch.io https://app.zencoder.com 'self'".
", source: https://medium.com/ (0)
 Logging in to Medium by using Google
Traceback (most recent call last):
  File "Grab_that_article_on_Medium.py", line 66, in <module>
    user = driver.find_element_by_xpath('//*[@id="password"]/div[1]/div/div[1]/input')
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="password"]/div[1]/div/div[1]/input"}
  (Session info: headless chrome=71.0.3578.80)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17134 x86_64)
```

**Comment by ZER-0-NE** [comment]
Interesting. @knightcube 
I think we can just pass if this situation arises or maybe catch an error and ask them to turn it off? 
Or Do you have something else in mind?
